---
title: "Baseball"
author: "Ryan Moorhead"
date: "12/7/2018"
output: 
 html_notebook
  
---

```{r setup, include=FALSE}
library(DataComputing)
library(mosaic)
library(tidyverse)
library(ggplot2)
library(rpart.plot)
```


```{r}
Batting <- read.csv("2018 Batting Stats Min. 50 AB.csv")
Pitching <- read.csv("2018 Pitching Stats Min. 10 IP.csv")
FansBat <- read.csv("Fans 2018 Batting Projections.csv")
FansPitch <- read.csv("Fans 2018 Pitching Projections.csv")
SteamBat <- read.csv("Steamer 2018 Batting Projections.csv")
SteamPitch <- read.csv("Steamer 2018 Pitching Projections.csv")
ZipsBat <- read.csv("ZiPS 2018 Batting Projections.csv")
ZipsPitch <- read.csv("ZiPS 2018 Pitching Projections.csv")
```

```{r}
Batting %>%
  head(3)
Pitching %>%
  head(3)
FansBat %>%
  head(3)
FansPitch %>%
  head(3)
SteamBat %>%
  head(3)
SteamPitch %>%
  head(3)
ZipsBat %>%
  head(3)
ZipsPitch %>%
  head(3)

```

```{r}
names(Batting) <- c("name", "team", "games", "pa", "homeruns", "runs", "rbi", "steals", "walkpercentage", "strikeoutpercentage", "iso", "babip", "average", "obp", "slugging", "woba", "wrc", "bsr","oruns", "druns", "war", "playerid")

names(Pitching) <-c("name", "team", "wins", "loses", "saves", "games", "gamesstarted", "innings", "strikeoutper9", "walksper9", "homerunsper9", "babip", "lob", "gb", "hrperfb", "era", "fip", "xfip", "war", "playerid")

FansBat <- FansBat %>%
  rename(fanwar = WAR, name = ï..Name, pid = playerid)
FansPitch <- FansPitch %>%
  rename(fanwar = WAR, name = ï..Name, pid = playerid)
SteamBat <- SteamBat %>%
  rename(steamwar = WAR, name = ï..Name, pid1 = playerid)
SteamPitch <- SteamPitch %>%
  rename(steamwar = WAR, name = ï..Name, pid1 = playerid)
ZipsBat <- ZipsBat %>%
  rename(zipwar = WAR, name = ï..Name, pid2 = playerid)
ZipsPitch <- ZipsPitch %>%
  rename(zipwar = WAR, name = ï..Name, pid2 = playerid)
```

```{r}
Batting %>%
  head(3)
Pitching %>%
  head(3)
```
```{r}
Bat1 <- Batting %>%
  inner_join(ZipsBat)

Bat1 <- Bat1 %>%
  group_by(name, war, zipwar) %>%
  summarise()

Bat2 <- Bat1 %>%
  inner_join(FansBat)

Bat2 <- Bat2 %>%
  group_by(name, war, zipwar, fanwar) %>%
  summarise()

Bat3 <- Bat2 %>%
  inner_join(SteamBat)

BatPrediction <- Bat3 %>%
  group_by(name, war, zipwar, fanwar, steamwar) %>%
  summarise()

Pit1 <- Pitching %>%
  inner_join(ZipsPitch)

Pit1 <- Pit1 %>%
  group_by(name, war, zipwar) %>%
  summarise()

Pit2 <- Pit1 %>%
  inner_join(FansPitch)

Pit2 <- Pit2 %>%
  group_by(name, war, zipwar, fanwar) %>%
  summarise()

Pit3 <- Pit2 %>%
  inner_join(SteamPitch)

PitchingPrediction <- Pit3 %>%
  group_by(name, war, zipwar, fanwar, steamwar) %>%
  summarise()
head(BatPrediction)
head(PitchingPrediction)
```
```{r}
BatPrediction <- BatPrediction %>%
  mutate(averagewar = (zipwar + fanwar + steamwar)/3)
PitchPrediction <- BatPrediction %>%
  mutate(averagewar = (zipwar + fanwar + steamwar)/3)

HittersRegression <- BatPrediction %>%
  lm(war ~ averagewar, data = .)
summary(HittersRegression)

HittersRegressionFan <- BatPrediction %>%
  lm(war ~ fanwar, data = .)
summary(HittersRegressionFan)

HittersRegressionSteam <- BatPrediction %>%
  lm(war ~ steamwar, data = .)
summary(HittersRegressionSteam)

HittersRegressionZip <- BatPrediction %>%
  lm(war ~ zipwar, data = .)
summary(HittersRegressionZip)
```
```{r}
PitchersRegression <- PitchPrediction %>%
  lm(war ~ averagewar, data = .)
summary(PitchersRegression)

PitchersRegressionFan <- PitchPrediction %>%
  lm(war ~ fanwar, data = .)
summary(PitchersRegressionFan)

PitchersRegressionSteam <- PitchPrediction %>%
  lm(war ~ steamwar, data = .)
summary(PitchersRegressionSteam)

PitchersRegressionZip <- PitchPrediction %>%
  lm(war ~ zipwar, data = .)
summary(PitchersRegressionZip)
```

```{r}
Pitching <- Pitching %>%
  mutate(ks = strikeoutper9 * innings / 9) %>%
  mutate(bb = walksper9 * innings / 9) %>%
  mutate(hr = homerunsper9 * innings / 9)
```

```{r}
Batting <- Batting %>%
  mutate(paperhomerun = pa / homeruns)
```

```{r}
Batting %>%
  ggplot(aes(x = average, y = war)) +
  geom_point()
Batting %>%
  ggplot(aes(x = wrc, y = war)) +
  geom_point()
Batting %>%
  ggplot(aes(x = homeruns, y = war)) +
  geom_point()
Batting %>%
  ggplot(aes(x = paperhomerun, y = war)) +
  geom_point()

Batting %>%
  group_by(name, paperhomerun, war) %>%
  filter(paperhomerun != "Inf") %>%
  summarise() %>%
  arrange(paperhomerun)
```

```{r}
Pitching %>%
  ggplot(aes(x = innings, y = war)) +
  geom_point()
Pitching %>%
  ggplot(aes(x = ks, y = war)) +
  geom_point()
Pitching %>%
  ggplot(aes(x = bb, y = war)) +
  geom_point()
Pitching %>%
  ggplot(aes(x = hr, y = war)) +
  geom_point()
Pitching %>%
  ggplot(aes(x = era, y = war)) +
  geom_point()
Pitching %>%
  ggplot(aes(x = fip, y = war)) +
  geom_point()
Pitching %>%
  ggplot(aes(x = wins, y = war)) +
  geom_point()
```

```{r}

Reggression <- Batting %>%
  filter(paperhomerun != "Inf") %>%
  lm(war ~ paperhomerun, data = .)
summary(Reggression)
```
```{r}

model4 <- Pitching %>%
  lm(war ~ ks, data = .)

summary(model4)
```

```{r}
model2 <- Batting %>%
  rpart(war ~ average + homeruns + wrc + pa + steals + rbi + runs + paperhomerun, data = .)

prp(model2)
```

```{r}
model3 <- Pitching %>%
  rpart(war ~ innings + era + ks + fip + bb + hr, data = .)

prp(model3)
```
